laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('a-infinity', 'InfinityController@index')->name('a-infinity');
    Route::get('servicos', 'ServicosController@index')->name('servicos');
    Route::get('projetos/{categoria_slug?}', 'ProjetosController@index')->name('projetos');
    Route::get('projetos/{categoria_slug}/{projeto_slug}', 'ProjetosController@show')->name('projetos.show');
    Route::get('midia', 'MidiaController@index')->name('midia');
    Route::get('midia/{midia_slug}', 'MidiaController@show')->name('midia.show');
    Route::get('clientes', 'ClientesController@index')->name('clientes');
    Route::get('imoveis', 'ImoveisController@index')->name('imoveis');
    Route::get('imoveis/{imovel_slug}', 'ImoveisController@show')->name('imoveis.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en') Session::put('locale', $idioma);
        return redirect()->route('home');
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('imoveis', 'ImoveisController');
        Route::get('imoveis/{imoveis}/imagens/clear', [
            'as'   => 'painel.imoveis.imagens.clear',
            'uses' => 'ImoveisImagensController@clear'
        ]);
        Route::resource('imoveis.imagens', 'ImoveisImagensController');

        Route::resource('projetos/categorias', 'ProjetosCategoriasController');
        Route::resource('projetos', 'ProjetosController');
        Route::get('projetos/{projetos}/imagens/clear', [
            'as'   => 'painel.projetos.imagens.clear',
            'uses' => 'ProjetosImagensController@clear'
        ]);
        Route::resource('projetos.imagens', 'ProjetosImagensController');
        Route::get('projetos/{projetos}/imagens-destaque/clear', [
            'as'   => 'painel.projetos.imagens-destaque.clear',
            'uses' => 'ProjetosImagensDestaqueController@clear'
        ]);
        Route::resource('projetos.imagens-destaque', 'ProjetosImagensDestaqueController');
        Route::resource('clientes', 'ClientesController');
		Route::resource('midia', 'MidiaController');
        Route::get('midia/{midia}/imagens/clear', [
            'as'   => 'painel.midia.imagens.clear',
            'uses' => 'MidiaImagensController@clear'
        ]);
        Route::resource('midia.imagens', 'MidiaImagensController');
		Route::resource('a-infinity', 'AInfinityController', ['only' => ['index', 'update']]);
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
		Route::resource('servicos/abertura', 'ServicosAberturaController', ['only' => ['index', 'update']]);
		Route::resource('servicos', 'ServicosController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
        Route::resource('newsletter', 'NewsletterController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AInfinityController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AInfinityRequest;
use App\Http\Controllers\Controller;

use App\Models\AInfinity;

class AInfinityController extends Controller
{
    public function index()
    {
        $registro = AInfinity::first();

        return view('painel.a-infinity.edit', compact('registro'));
    }

    public function update(AInfinityRequest $request, AInfinity $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = AInfinity::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = AInfinity::upload_imagem_2();
            if (isset($input['imagem_3'])) $input['imagem_3'] = AInfinity::upload_imagem_3();
            if (isset($input['imagem_4'])) $input['imagem_4'] = AInfinity::upload_imagem_4();
            if (isset($input['imagem_5'])) $input['imagem_5'] = AInfinity::upload_imagem_5();
            if (isset($input['imagem_6'])) $input['imagem_6'] = AInfinity::upload_imagem_6();
            if (isset($input['pessoas_chave_foto'])) $input['pessoas_chave_foto'] = AInfinity::upload_pessoas_chave_foto();

            $registro->update($input);

            return redirect()->route('painel.a-infinity.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ClientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Cliente;
use App\Helpers\CropImage;

class ClientesController extends Controller
{
    private $image_config = [
        'width'   => 185,
        'height'  => 120,
        'cliente' => true,
        'path'    => 'assets/img/clientes/'
    ];

    public function index()
    {
        $imagens = Cliente::ordenados()->get();

        return view('painel.clientes.index', compact('imagens'));
    }

    public function show(Cliente $imagem)
    {
        return $imagem;
    }

    public function store(ClientesRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $imagem = Cliente::create($input);

            $view = view('painel.clientes.imagem', compact('imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: '.$e->getMessage();

        }
    }

    public function destroy(Cliente $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.clientes.index')
                             ->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\HomeRequest;
use App\Http\Controllers\Controller;

use App\Models\Home;

class HomeController extends Controller
{
    public function index()
    {
        $registro = Home::first();

        return view('painel.home.edit', compact('registro'));
    }

    public function update(HomeRequest $request, Home $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = Home::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = Home::upload_imagem_2();
            if (isset($input['imagem_3'])) $input['imagem_3'] = Home::upload_imagem_3();
            if (isset($input['projetos_imagem'])) $input['projetos_imagem'] = Home::upload_projetos_imagem();

            $registro->update($input);

            return redirect()->route('painel.home.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ImoveisController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ImovelRequest;
use App\Http\Controllers\Controller;

use App\Models\Imovel;
use App\Helpers\CropImage;

class ImoveisController extends Controller
{
    private $categorias;

    private $image_config = [
        'width'   => 365,
        'height'  => 245,
        'path'    => 'assets/img/imoveis/thumbs/'
    ];

    public function index(Request $request)
    {
        $imoveis = Imovel::ordenados()->get();

        return view('painel.imoveis.index', compact('imoveis'));
    }

    public function create()
    {
        return view('painel.imoveis.create');
    }

    public function store(ImovelRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Imovel::create($input);
            return redirect()->route('painel.imoveis.index')->with('success', 'Imóvel adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar imóvel: '.$e->getMessage()]);

        }
    }

    public function edit(Imovel $imovel)
    {
        return view('painel.imoveis.edit', compact('imovel'));
    }

    public function update(ImovelRequest $request, Imovel $imovel)
    {
        try {

            $input = $request->all();
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $imovel->update($input);
            return redirect()->route('painel.imoveis.index')->with('success', 'Imóvel alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar imóvel: '.$e->getMessage()]);

        }
    }

    public function destroy(Imovel $projeto)
    {
        try {

            $projeto->delete();
            return redirect()->route('painel.imoveis.index')->with('success', 'Imóvel excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imóvel: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ImoveisImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ImovelImagemRequest;
use App\Http\Controllers\Controller;

use App\Models\Imovel;
use App\Models\ImovelImagem;
use App\Helpers\CropImage;

class ImoveisImagensController extends Controller
{
    private $image_config = [
        [
            'width'   => 230,
            'height'  => 175,
            'path'    => 'assets/img/imoveis/imagens/thumbs/'
        ],
        [
            'width'   => 730,
            'height'  => 410,
            'path'    => 'assets/img/imoveis/imagens/thumbs-destaque/'
        ],
        [
            'width'   => 1980,
            'height'  => null,
            'upsize'  => true,
            'path'    => 'assets/img/imoveis/imagens/'
        ]
    ];

    public function index(Imovel $imovel)
    {
        $imagens = $imovel->imagens;

        return view('painel.imoveis.imagens.index', compact('imagens', 'imovel'));
    }

    public function show(Imovel $imovel, ImovelImagem $imagem)
    {
        return $imagem;
    }

    public function create(Imovel $imovel)
    {
        return view('painel.imoveis.imagens.create', compact('imovel'));
    }

    public function store(Imovel $imovel, ImovelImagemRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            $input['imovel_id'] = $imovel->id;

            $imagem = ImovelImagem::create($input);

            $view = view('painel.imoveis.imagens.imagem', compact('imovel', 'imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: '.$e->getMessage();

        }
    }

    public function destroy(Imovel $imovel, ImovelImagem $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.imoveis.imagens.index', $imovel)
                ->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }

    public function clear(Imovel $imovel)
    {
        try {

            $imovel->imagens()->delete();
            return redirect()->route('painel.imoveis.imagens.index', $imovel)
                             ->with('success', 'Imagens excluídas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagens: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
	<li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.banners.index') }}">Banners</a>
	</li>
    <li @if(str_is('painel.home*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.home.index') }}">Home</a>
    </li>
    <li @if(str_is('painel.a-infinity*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.a-infinity.index') }}">A Infinity</a>
    </li>
	<li @if(str_is('painel.servicos*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.servicos.index') }}">Serviços</a>
	</li>
    <li @if(str_is('painel.projetos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.projetos.index') }}">Projetos</a>
    </li>
    <li @if(str_is('painel.imoveis*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.imoveis.index') }}">Imóveis</a>
    </li>
    <li @if(str_is('painel.clientes*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.clientes.index') }}">Clientes</a>
    </li>
    <li @if(str_is('painel.midia*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.midia.index') }}">Mídia</a>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
    <li @if(str_is('painel.newsletter*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.newsletter.index') }}">Newsletter</a>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/painel.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('/') }}">{{ config('site.name') }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            Sistema <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/vendor/jquery/dist/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/bootswatch-dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootbox.js/bootbox.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/painel.js') }}"></script>
</body>
</html>